import {FireCharacter} from './characters/fire.js';
import {WaterCharacter} from './characters/water.js';
import {EarthCharacter} from './characters/earth.js';
import {AirCharacter} from './characters/air.js';
import {Essence,ELEMENTS} from './selection/essence.js';
import {Portal} from './portal/portal.js';
import {burst,updateParticles} from './entry-effects.js';
import {runTransformation} from './transformation/transformation.js';
import {ElementalMap} from './map/elemental-map.js';
import {BattleRuntime} from './battle/battle-runtime.js';
const C={fuego:FireCharacter,agua:WaterCharacter,tierra:EarthCharacter,aire:AirCharacter};
const scene=new THREE.Scene(),canvas=document.querySelector('#game');const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.6));renderer.shadowMap.enabled=true;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;const camera=new THREE.PerspectiveCamera(58,1,.1,900),clock=new THREE.Clock();
scene.add(new THREE.HemisphereLight(0x9bb9df,0x160d1b,1.6));const sun=new THREE.DirectionalLight(0xffdfbd,2.7);sun.position.set(-35,70,30);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);
const keys={};const st={phase:'selection',time:24,total:24,normal:null,player:null,chosen:null,essences:[],portal:null,fx:[],map:null,battle:null};const ui=(id,v)=>{const e=document.querySelector(id);if(e)e.textContent=v};const mat=(c,e=0,i=0,r=.75)=>new THREE.MeshStandardMaterial({color:c,emissive:e,emissiveIntensity:i,roughness:r,metalness:.12});
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.code==='KeyE'||e.key.toLowerCase()==='e')interact();if(e.code==='Space')attack()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
function human(pos){const g=new THREE.Group(),b=new THREE.Mesh(new THREE.CapsuleGeometry(.34,.75,5,10),mat(0x20252e)),h=new THREE.Mesh(new THREE.SphereGeometry(.27,16,12),mat(0xb87959)),hair=new THREE.Mesh(new THREE.SphereGeometry(.29,12,8,0,Math.PI*2,0,Math.PI*.55),mat(0x111318));b.position.y=.85;h.position.y=1.7;hair.position.y=1.84;g.add(b,h,hair);for(const x of[-.14,.14]){const l=new THREE.Mesh(new THREE.CapsuleGeometry(.12,.62,4,8),mat(0x111318));l.position.set(x,.12,0);g.add(l)}for(const x of[-.46,.46]){const a=new THREE.Mesh(new THREE.CapsuleGeometry(.12,.62,4,8),mat(0x111318));a.position.set(x,1.05,0);a.rotation.z=x<0?-.18:.18;g.add(a)}g.position.copy(pos);g.traverse(o=>{if(o.isMesh)o.castShadow=true});scene.add(g);return g}
function move(o,dt,s){if(!o)return;const x=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),z=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0);const v=new THREE.Vector3(x,0,z);if(v.lengthSq()){v.normalize();const next=o.position.clone().addScaledVector(v,dt*s);if(st.map&&st.phase==='battle'){if(!st.map.collides(next,.65))o.position.copy(next);else o.position.copy(st.map.resolve(next,.65))}else o.position.copy(next);o.rotation.y=Math.atan2(v.x,v.z)}}
function nearest(){let b=null,d=1e9;for(const e of st.essences)if(!e.taken){const n=e.group.position.distanceTo(st.normal.position);if(n<d){d=n;b=e}}return b}
function entry(){scene.background=new THREE.Color(0x040711);scene.fog=new THREE.FogExp2(0x070a16,.022);const stars=new THREE.BufferGeometry(),p=new Float32Array(1500);for(let i=0;i<500;i++){const a=Math.random()*6.28,r=55+Math.random()*95;p[i*3]=Math.cos(a)*r;p[i*3+1]=-10+Math.random()*85;p[i*3+2]=Math.sin(a)*r-15}stars.setAttribute('position',new THREE.BufferAttribute(p,3));scene.add(new THREE.Points(stars,new THREE.PointsMaterial({color:0x9ebcff,size:.16,transparent:true,opacity:.8,depthWrite:false})));const base=new THREE.Mesh(new THREE.CylinderGeometry(20.5,22,.8,96),mat(0x111827,0x251a3d,.35));base.position.y=-.55;base.receiveShadow=true;scene.add(base);const top=new THREE.Mesh(new THREE.CylinderGeometry(19.7,19.7,.34,96),mat(0x30313b,0x16151e,.12,.95));top.position.y=-.05;scene.add(top);st.portal=new Portal(scene,new THREE.Vector3(0,.25,-10.8));['fuego','agua','tierra','aire'].forEach((k,i)=>{const a=i*Math.PI/2+Math.PI/4;st.essences.push(new Essence(scene,k,new THREE.Vector3(Math.cos(a)*7.5,2.1,Math.sin(a)*7.5)))});st.normal=human(new THREE.Vector3(0,.35,4));ui('#phaseMod','EL PORTAL DESPIERTA');ui('#timerMod','24');ui('#objectiveMod','TOMA UNA ESENCIA Y LLEGA AL PORTAL');ui('#elementNameMod','SIN ELEMENTO');ui('#elementEmojiMod','✦');ui('#feedMod','Muévete · usa E para tomar una esencia')}
function interact(){if(st.phase!=='selection')return;const e=nearest();if(e&&e.group.position.distanceTo(st.normal.position)<2.2){st.chosen=e.key;e.collect();st.phase='transform';st.time=1.7;st.total=1.7;ui('#phaseMod','DESPERTAR');ui('#objectiveMod','LA ESENCIA TE RECONOCE');ui('#feedMod','Transformación en curso…');runTransformation(scene,{group:st.normal},e.data,transform)}}
function transform(){const p=st.normal.position.clone(),k=st.chosen;scene.remove(st.normal);st.player=new C[k]({isPlayer:true});st.player.group.position.copy(p);scene.add(st.player.group);burst(scene,st.fx,p,ELEMENTS[k].glow,100,5);st.phase='portal';st.time=10;st.total=10;ui('#phaseMod','PORTAL ABIERTO');ui('#timerMod','10');ui('#objectiveMod','¡CORRE AL PORTAL!');ui('#feedMod','Tu elemento está despierto')}
function drop(){st.phase='drop';for(const o of[...scene.children])if(o!==sun&&o.type!=='HemisphereLight')scene.remove(o);st.fx=[];st.essences=[];st.portal=null;st.map=new ElementalMap(scene,{worldRadius:430,playRadius:155,seed:1337});st.player.group.position.set(0,28,0);scene.add(st.player.group);const col=ELEMENTS[st.chosen].color,can=new THREE.Mesh(new THREE.SphereGeometry(4.5,24,12,0,Math.PI*2,0,Math.PI*.5),mat(col,col,.3));can.scale.y=.62;can.position.y=5.8;st.player.group.add(can);st.player.group.userData.parachute=can;st.player.group.userData.parachuteOpen=true;ui('#phaseMod','CAÍDA AL MAPA');ui('#timerMod','—');ui('#objectiveMod','DESCIENDE · PREPÁRATE PARA LA BATALLA');ui('#feedMod',ELEMENTS[st.chosen].name.toUpperCase())}
function land(){const p=st.player.group,can=p.userData.parachute;if(can){p.remove(can);can.geometry.dispose();can.material.dispose()}p.userData.parachuteOpen=false;p.position.y=.7;st.phase='battle';st.battle=new BattleRuntime(scene,st.map,p,st.chosen);ui('#phaseMod','BATALLA');ui('#objectiveMod','DERROTA A LOS RIVALES · SOBREVIVE');ui('#feedMod','Ataque ✦ · Habilidad E')}
function attack(){if(st.phase==='battle')st.battle.attack()}function special(){if(st.phase==='battle')st.battle.special()}
addEventListener('keydown',e=>{if(e.code==='KeyE'&&st.phase==='battle')special()});
function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.035),t=clock.elapsedTime;updateParticles(st.fx,dt);if(st.portal)st.portal.update(t,st.phase==='pull'?1:Math.max(0,1-st.time/st.total));if(st.phase==='selection'){st.time-=dt;ui('#timerMod',Math.ceil(Math.max(0,st.time)));st.essences.forEach(e=>e.update(t,e.group.position.distanceTo(st.normal.position)<2.4));move(st.normal,dt,4.8);if(st.time<=0){st.phase='pull';st.time=5;st.total=5}}else if(st.phase==='transform'){st.time-=dt}else if(st.phase==='portal'){st.time-=dt;move(st.player.group,dt,5.8);if(st.player.group.position.distanceTo(st.portal.position)<5.2||st.time<=0)drop()}else if(st.phase==='pull'){st.time-=dt;st.portal?.attract(st.normal,dt,1-st.time/st.total);if(st.time<=0)drop()}else if(st.phase==='drop'){st.player.group.position.y-=dt*2.8;camera.position.lerp(new THREE.Vector3(st.player.group.position.x,st.player.group.position.y+13,st.player.group.position.z+18),.05);camera.lookAt(st.player.group.position);if(st.player.group.position.y<=.7)land()}else if(st.phase==='battle'){st.map?.update(dt);move(st.player.group,dt,6.5);st.battle?.update(dt);camera.position.lerp(new THREE.Vector3(st.player.group.position.x,9,st.player.group.position.z+14),.08);camera.lookAt(st.player.group.position.x,1,st.player.group.position.z)}renderer.render(scene,camera)}
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();entry();loop();
