import { FireCharacter } from './characters/fire.js';
import { WaterCharacter } from './characters/water.js';
import { EarthCharacter } from './characters/earth.js';
import { AirCharacter } from './characters/air.js';

const DATA={
 fuego:{name:'FUEGO',emoji:'🔥',main:0xff3b08,glow:0xffb000,desc:'Explosión · quemadura · presión',klass:FireCharacter},
 agua:{name:'AGUA',emoji:'💧',main:0x168cff,glow:0x7de9ff,desc:'Control · curación · oleaje',klass:WaterCharacter},
 tierra:{name:'TIERRA',emoji:'🪨',main:0x9a6531,glow:0xe3ad63,desc:'Defensa · impacto · dominio',klass:EarthCharacter},
 aire:{name:'AIRE',emoji:'🌀',main:0x9beaff,glow:0xffffff,desc:'Velocidad · corte · movilidad',klass:AirCharacter}
};
const START=Object.keys(DATA); const $=s=>document.querySelector(s);
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x07111c); scene.fog=new THREE.FogExp2(0x07111c,.0026);
const canvas=$('#game'); const renderer=new THREE.WebGLRenderer({canvas,antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,1.7)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.18;
const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,1400); const hemi=new THREE.HemisphereLight(0x8bbcff,0x17100b,1.25); const sun=new THREE.DirectionalLight(0xffe2bd,2.5); sun.position.set(-55,85,35); sun.castShadow=true; sun.shadow.mapSize.set(2048,2048); scene.add(hemi,sun);
let player=null,allies=[],enemies=[],loot=[],particles=[],cracks=[],phase='selection',selected=null,timer=16,zoneRadius=112,collapseStage=0,cooldown=0,specialCooldown=0,score=0,zone=null; const keys={}; const clock=new THREE.Clock();
function material(c,e=0,ei=.25,r=.78){return new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:.12,emissive:e,emissiveIntensity:ei})} function additive(c,o=.8){return new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:o,blending:THREE.AdditiveBlending,depthWrite:false})} function ui(id,v){const e=$(id);if(e)e.textContent=v}
function burst(pos,color,n=18,power=2){for(let i=0;i<n;i++){const q=new THREE.Mesh(new THREE.IcosahedronGeometry(.045+Math.random()*.055,0),additive(color,.9));q.position.copy(pos);q.userData={v:new THREE.Vector3((Math.random()-.5)*power,(Math.random()-.25)*power,(Math.random()-.5)*power),life:.35+Math.random()*.7};scene.add(q);particles.push(q)}}
function makeSky(){const sky=new THREE.Mesh(new THREE.SphereGeometry(600,32,16),new THREE.MeshBasicMaterial({color:0x0a1727,side:THREE.BackSide}));scene.add(sky);for(let i=0;i<28;i++){const c=new THREE.Mesh(new THREE.SphereGeometry(2+Math.random()*4,10,8),new THREE.MeshBasicMaterial({color:0x29435a,transparent:true,opacity:.22,depthWrite:false}));c.scale.x=2.5;c.position.set((Math.random()-.5)*420,65+Math.random()*55,(Math.random()-.5)*420);scene.add(c)}}
function ground(){const island=new THREE.Mesh(new THREE.CylinderGeometry(122,128,3,96),material(0x243a31));island.position.y=-1.5;island.receiveShadow=true;scene.add(island);const grass=new THREE.Mesh(new THREE.CylinderGeometry(118,120,.8,96),material(0x31503b));grass.position.y=.1;grass.receiveShadow=true;scene.add(grass);for(let i=0;i<11;i++){const a=i*Math.PI*2/11+.2,r=90+Math.random()*20,rock=new THREE.Mesh(new THREE.DodecahedronGeometry(3+Math.random()*4,0),material(0x35434a));rock.scale.y=.55;rock.position.set(Math.cos(a)*r,1,Math.sin(a)*r);rock.castShadow=true;scene.add(rock)}}
function path(x,z,rot,len=45,w=5){const p=new THREE.Mesh(new THREE.BoxGeometry(w,.12,len),material(0x5b4b3b));p.position.set(x,.5,z);p.rotation.y=rot;scene.add(p)}
function house(x,z,s=1,rot=0,name='Casa'){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(7*s,5*s,6*s),material(0x514033));body.position.y=2.5*s;body.castShadow=true;const roof=new THREE.Mesh(new THREE.ConeGeometry(5.2*s,3.4*s,4),material(0x542d29));roof.position.y=6.6*s;roof.rotation.y=Math.PI/4;roof.castShadow=true;g.add(body,roof);for(const sx of[-1,1]){const win=new THREE.Mesh(new THREE.PlaneGeometry(1.2*s,1.3*s),additive(0xffc86b,.7));win.position.set(sx*1.8*s,2.8*s,3.03*s);g.add(win)}g.position.set(x,.3,z);g.rotation.y=rot;g.userData={name};scene.add(g)}
function makeShrine(){const g=new THREE.Group();g.add(new THREE.Mesh(new THREE.CylinderGeometry(9,11,1,8),material(0x211b2d)));START.forEach((k,i)=>{const p=new THREE.Mesh(new THREE.CylinderGeometry(.45,.65,6,8),material(DATA[k].main));const a=i*Math.PI/2;p.position.set(Math.cos(a)*6,3,Math.sin(a)*6);g.add(p)});const core=new THREE.Mesh(new THREE.IcosahedronGeometry(1.5,2),additive(0xc17aff,.8));core.position.y=4;g.add(core);g.position.y=.5;scene.add(g)}
function makeZone(){const ring=new THREE.Mesh(new THREE.RingGeometry(111,112,160),additive(0xff3555,.9));ring.rotation.x=-Math.PI/2;ring.position.y=.7;scene.add(ring);const inner=new THREE.Mesh(new THREE.RingGeometry(110.5,111,160),new THREE.MeshBasicMaterial({color:0xff7180,transparent:true,opacity:.12,side:THREE.DoubleSide}));inner.rotation.x=-Math.PI/2;inner.position.y=.68;scene.add(inner);zone={ring,inner}}
function world(){makeSky();ground();path(0,0,0,190,5);path(0,0,Math.PI/2,190,5);for(let i=0;i<10;i++){const a=i*Math.PI*2/10,r=30+Math.random()*58;house(Math.cos(a)*r,Math.sin(a)*r,.72+Math.random()*.38,a+.8,['Casa de Cura','Refugio','Arsenal','Torre del Nexo'][i%4])}for(let i=0;i<95;i++){const a=Math.random()*Math.PI*2,r=12+Math.random()*103,x=Math.cos(a)*r,z=Math.sin(a)*r,trunk=new THREE.Mesh(new THREE.CylinderGeometry(.14,.24,1.6,6),material(0x3c2a1d));trunk.position.set(x,1,z);const crown=new THREE.Mesh(new THREE.IcosahedronGeometry(.9+Math.random()*1.1,0),material(i%3?0x28553a:0x326947));crown.position.set(x,2.1,z);crown.castShadow=true;scene.add(trunk,crown)}for(let i=0;i<18;i++){const a=Math.random()*Math.PI*2,r=15+Math.random()*90,crystal=new THREE.Mesh(new THREE.OctahedronGeometry(.35+Math.random()*.4,0),additive([0x8b6cff,0x45d7ff,0xff5d32][i%3],.55));crystal.position.set(Math.cos(a)*r,.8,Math.sin(a)*r);scene.add(crystal)}makeShrine();makeZone()}
function fracture(r){for(let i=0;i<72;i++){const a=i/72*Math.PI*2,inner=r-2-Math.random()*2,outer=r+4+Math.random()*3,geo=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(Math.cos(a)*inner,.7,Math.sin(a)*inner),new THREE.Vector3(Math.cos(a)*outer,.75,Math.sin(a)*outer)]),line=new THREE.Line(geo,new THREE.LineBasicMaterial({color:0xff4058,transparent:true,opacity:.8}));scene.add(line);cracks.push(line)}burst(new THREE.Vector3(),0xff3b55,70,11)}
function portalScene(){while(scene.children.length>2)scene.remove(scene.children[2]);const g=new THREE.Group();g.add(new THREE.Mesh(new THREE.CylinderGeometry(19,20,.8,64),material(0x111827,0x321b5a,.5)));const halo=new THREE.Mesh(new THREE.TorusGeometry(5.4,.45,20,100),additive(0xc46cff,1));halo.position.y=4;g.add(halo);const core=new THREE.Mesh(new THREE.CircleGeometry(4.9,64),new THREE.MeshBasicMaterial({color:0x241040,transparent:true,opacity:.72,side:THREE.DoubleSide}));core.position.y=4;g.add(core);START.forEach((k,i)=>{const d=DATA[k],a=i*Math.PI/2-Math.PI/4,p=new THREE.Mesh(new THREE.CylinderGeometry(1.35,1.6,.65,24),material(0x171d2a,d.main,.5));p.position.set(Math.cos(a)*9,0,Math.sin(a)*9);g.add(p);const orb=new THREE.Mesh(new THREE.IcosahedronGeometry(.75,1),additive(d.main,.95));orb.position.set(p.position.x,1.1,p.position.z);g.add(orb);const light=new THREE.PointLight(d.main,1.3,9);light.position.copy(orb.position);g.add(light)});scene.add(g);camera.position.set(0,20,30);camera.lookAt(0,2,0);buildSelection()}
function buildSelection(){const panel=$('#selectionMod');panel.innerHTML='<div class="eyebrow">PRÓLOGO · 4 ESENCIAS</div><h1>ELIGE TU ELEMENTO</h1><p class="selectionDesc">El portal está despertando. Agarra una esencia antes de que te arrastre. Lo que domines hoy quedará contigo.</p><div class="elementGrid"></div><div class="selectionTip">TOCA UNA ESENCIA · 1–4 EN PC</div>';panel.style.display='flex';const grid=panel.querySelector('.elementGrid');START.forEach((k,i)=>{const d=DATA[k],b=document.createElement('button');b.className='elementChoice';b.style.color='#'+d.main.toString(16).padStart(6,'0');b.innerHTML=`<span class="bigEmoji">${d.emoji}</span><span><b>${d.name}</b><small>${d.desc}</small></span><kbd>${i+1}</kbd>`;b.onclick=()=>choose(k);grid.appendChild(b)})}
function choose(k){if(phase!=='selection')return;selected=k;phase='drop';$('#selectionMod').style.display='none';startDrop()}
function spawnCharacter(k,isPlayer,x,z){const c=new DATA[k].klass({isPlayer});c.group.position.set(x,32,z);c.group.scale.setScalar(isPlayer?1.2:1);c.health=100;c.shield=0;c.speedBoost=0;scene.add(c.group);return c}
function startDrop(){world();player=spawnCharacter(selected,true,0,0);allies=START.filter(k=>k!==selected).map((k,i)=>spawnCharacter(k,false,(i-1)*8,-7));enemies=START.map((k,i)=>spawnCharacter(k,false,55*Math.cos(i*Math.PI/2),55*Math.sin(i*Math.PI/2)));makeParachute();timer=7;ui('objectiveMod','DESCENSO · PREPARA TU ELEMENTO')}
function makeParachute(){const g=new THREE.Group(),d=DATA[selected],canopy=new THREE.Mesh(new THREE.SphereGeometry(4.7,28,14,0,Math.PI*2,0,Math.PI*.5),material(d.main,d.glow,.55,.55));canopy.scale.y=.62;canopy.position.y=6;g.add(canopy);for(let i=-2;i<=2;i++){const rope=new THREE.Mesh(new THREE.CylinderGeometry(.018,.018,3.4,5),additive(0xffffff,.7));rope.position.set(i*1.05,4.35,0);g.add(rope)}player.group.add(g);player.parachute=g}
function dropUpdate(dt){[player,...allies,...enemies].forEach(c=>c.group.position.y=Math.max(.2,c.group.position.y-dt*5.2));camera.position.lerp(new THREE.Vector3(player.group.position.x,player.group.position.y+14,player.group.position.z+19),.06);camera.lookAt(player.group.position.x,0,player.group.position.z);if(player.group.position.y<=.21){if(player.parachute){player.group.remove(player.parachute);player.parachute=null}startBattle()}}
function spawnLoot(){const types=[['cura',0x41e09a],['escudo',0x58bfff],['habilidad',0xc277ff],['velocidad',0xffd04d]];for(let i=0;i<32;i++){const a=Math.random()*Math.PI*2,r=15+Math.random()*90,t=types[i%4],g=new THREE.Group();g.add(new THREE.Mesh(new THREE.OctahedronGeometry(.38,1),additive(t[1],.9)));const ring=new THREE.Mesh(new THREE.TorusGeometry(.58,.035,6,24),additive(t[1],.55));ring.rotation.x=Math.PI/2;g.add(ring);g.position.set(Math.cos(a)*r,.9,Math.sin(a)*r);g.userData={type:t[0]};scene.add(g);loot.push(g)}}
function startBattle(){phase='battle';timer=150;spawnLoot();ui('objectiveMod','SOBREVIVE · SAQUEA · DOMINA')}
function projectile(color,pos,dir){const g=new THREE.Group();g.add(new THREE.Mesh(new THREE.IcosahedronGeometry(.28,1),additive(color,1)));g.add(new THREE.Mesh(new THREE.SphereGeometry(.62,12,8),additive(color,.14)));g.position.copy(pos);scene.add(g);let life=1.2;function fly(){if(!g.parent)return;g.position.addScaledVector(dir,0.45);burst(g.position,color,1,.25);life-=1/60;if(life<=0){g.removeFromParent();burst(g.position,color,30,2.5);return}requestAnimationFrame(fly)}fly()}
function castSpecial(){if(phase!=='battle'||specialCooldown>0)return;specialCooldown=3.2;const d=DATA[selected],p=player.group.position.clone(),ring=new THREE.Mesh(new THREE.RingGeometry(.4,7.5,80),additive(d.main,.55));ring.rotation.x=-Math.PI/2;ring.position.set(p.x,.8,p.z);scene.add(ring);burst(p,d.glow,75,7);setTimeout(()=>ring.parent&&ring.removeFromParent(),650);score+=50;ui('feedMod','✦ HABILIDAD ESPECIAL · +50')}
function castAttack(){if(phase!=='battle'||cooldown>0)return;cooldown=.42;const d=DATA[selected],p=player.group.position.clone();p.y+=1.15;const dir=new THREE.Vector3(0,0,-1).applyQuaternion(player.group.quaternion).normalize();projectile(d.main,p,dir);burst(p,d.glow,12,1.4);score+=10}
function useLoot(o){const t=o.userData.type;if(t==='cura')player.health=Math.min(100,player.health+30);if(t==='escudo')player.shield=12;if(t==='velocidad')player.speedBoost=8;if(t==='habilidad')score+=30;ui('feedMod',t==='cura'?'✚ CURA +30':t==='escudo'?'⬟ ESCUDO +12s':t==='velocidad'?'➤ VELOCIDAD +8s':'✦ DOMINIO +30');burst(o.position,DATA[selected].glow,22,2.5);o.removeFromParent();loot=loot.filter(x=>x!==o)}
function move(dt){const d=new THREE.Vector3((keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),0,(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0));if(d.lengthSq())d.normalize();const speed=player.speedBoost>0?13:8;player.velocity.lerp(d.multiplyScalar(speed),Math.min(1,dt*9));if(d.lengthSq())player.group.rotation.y=Math.atan2(d.x,d.z);player.update(dt,clock.elapsedTime);player.group.position.x=Math.max(-114,Math.min(114,player.group.position.x));player.group.position.z=Math.max(-114,Math.min(114,player.group.position.z));if(player.speedBoost>0)player.speedBoost-=dt;allies.forEach((c,i)=>{const target=player.group.position.clone().add(new THREE.Vector3(Math.cos(clock.elapsedTime+i*2)*7,0,Math.sin(clock.elapsedTime+i*2)*7));c.velocity.lerp(target.sub(c.group.position).multiplyScalar(.5),dt*1.5);c.update(dt,clock.elapsedTime)});enemies.forEach((c,i)=>{const target=new THREE.Vector3(Math.cos(clock.elapsedTime*.25+i)*60,0,Math.sin(clock.elapsedTime*.25+i)*60);c.velocity.lerp(target.sub(c.group.position).multiplyScalar(.3),dt);c.update(dt,clock.elapsedTime)});camera.position.lerp(new THREE.Vector3(player.group.position.x,player.group.position.y+13,player.group.position.z+17),.08);camera.lookAt(player.group.position.x,0,player.group.position.z)}
function collapse(){const elapsed=150-timer,stage=Math.min(8,Math.floor(elapsed/18));if(stage>collapseStage){collapseStage=stage;zoneRadius=112-stage*11;zone.ring.scale.set(zoneRadius/112,zoneRadius/112,1);zone.inner.scale.set(zoneRadius/111,zoneRadius/111,1);fracture(zoneRadius);ui('objectiveMod',`⚠ FRACTURA ${stage}/8 · EL MAPA SE ESTÁ ROMPIENDO`)}if(Math.hypot(player.group.position.x,player.group.position.z)>zoneRadius){player.damage(.65);burst(player.group.position,0xff3555,2,1)}}
function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.05),t=clock.elapsedTime;cooldown=Math.max(0,cooldown-dt);specialCooldown=Math.max(0,specialCooldown-dt);if(phase==='selection'){timer=Math.max(0,timer-dt);ui('timerMod',Math.ceil(timer))}else if(phase==='drop'){timer=Math.max(0,timer-dt);ui('timerMod',Math.ceil(timer));dropUpdate(dt)}else if(phase==='battle'){timer=Math.max(0,timer-dt);ui('timerMod',Math.ceil(timer));move(dt);collapse();loot.forEach(o=>{o.rotation.y+=dt*2;o.position.y=.8+Math.sin(t*3+o.position.x)*.12;if(player.group.position.distanceTo(o.position)<1.6)useLoot(o)});if(timer<=0){phase='end';ui('objectiveMod','VICTORIA · TU DOMINIO ELEMENTAL AUMENTA')}}particles.forEach(p=>{p.position.addScaledVector(p.userData.v,dt);p.userData.v.y-=dt*2.6;p.userData.life-=dt;if(p.userData.life<=0)p.removeFromParent()});particles=particles.filter(p=>p.parent);ui('scoreMod',`✦ ${score}`);ui('hpMod',`HP ${Math.ceil(player?.health||100)}`);ui('elementEmojiMod',selected?DATA[selected].emoji:'✦');ui('elementNameMod',selected?DATA[selected].name:'SIN ELEMENTO');if($('#hpBarMod'))$('#hpBarMod').style.width=(player?.health||100)+'%';renderer.render(scene,camera)}
function orientation(){try{screen.orientation?.lock?.('landscape').catch(()=>{});document.documentElement.requestFullscreen?.({navigationUI:'hide'}).catch(()=>{})}catch(e){}}
addEventListener('pointerdown',orientation,{once:true,passive:true});addEventListener('keydown',orientation,{once:true,passive:true});addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.code==='Space'||e.key.toLowerCase()==='q')castAttack();if(e.key.toLowerCase()==='e')castSpecial();START.forEach((k,i)=>{if(e.key===String(i+1))choose(k)})});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);addEventListener('pointerdown',e=>{if(e.target===canvas&&phase==='battle')castAttack()});document.querySelectorAll('.abilities button').forEach((b,i)=>b.addEventListener('pointerdown',e=>{e.preventDefault();i===1?castSpecial():castAttack()}));addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});portalScene();loop();
