import { ElementalMap } from './map/map.js';
import { FireCharacter } from './characters/fire.js';
import { WaterCharacter } from './characters/water.js';
import { EarthCharacter } from './characters/earth.js';
import { AirCharacter } from './characters/air.js';
import { ATTACKS } from './attacks/attacks.js';
import { GameUI } from './ui/ui.js';

const ELEMENTS={fuego:{name:'Fuego',emoji:'🔥',color:0xff4d00,klass:FireCharacter},agua:{name:'Agua',emoji:'💧',color:0x29aaff,klass:WaterCharacter},tierra:{name:'Tierra',emoji:'🪨',color:0xb27a3e,klass:EarthCharacter},aire:{name:'Aire',emoji:'🌀',color:0xbceeff,klass:AirCharacter}};
const state={phase:'lobby',selected:null,time:20,mastery:JSON.parse(localStorage.getItem('fe_mod_mastery')||'{}')};
const canvas=document.querySelector('#game'); const renderer=new THREE.WebGLRenderer({canvas,antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=true; renderer.outputEncoding=THREE.sRGBEncoding; renderer.toneMapping=THREE.ACESFilmicToneMapping;
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x07101b); scene.fog=new THREE.FogExp2(0x07101b,.0035);
const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,1000); camera.position.set(0,35,34); camera.lookAt(0,0,0);
scene.add(new THREE.HemisphereLight(0x8ab8ff,0x17100c,1)); const sun=new THREE.DirectionalLight(0xffe7c2,2);sun.position.set(-30,60,20);sun.castShadow=true;scene.add(sun);
const ui=new GameUI(document.body); let map=null,player=null,players=[],clock=new THREE.Clock(); let yaw=0,keys={};
function portalScene(){
 const floor=new THREE.Mesh(new THREE.CircleGeometry(22,64),new THREE.MeshStandardMaterial({color:0x111827,roughness:.55,metalness:.25}));floor.rotation.x=-Math.PI/2;floor.position.y=-.35;scene.add(floor);
 for(let i=0;i<4;i++){const k=['fuego','agua','tierra','aire'][i],E=ELEMENTS[k],a=i*Math.PI/2-Math.PI/4; const p=new THREE.Mesh(new THREE.CylinderGeometry(1.1,1.1,.35,24),new THREE.MeshStandardMaterial({color:E.color,emissive:E.color,emissiveIntensity:.45}));p.position.set(Math.cos(a)*8,0,Math.sin(a)*8);p.userData.element=k;scene.add(p); const c=new THREE.Mesh(new THREE.TorusGeometry(1.5,.11,10,32),new THREE.MeshBasicMaterial({color:E.color,transparent:true,opacity:.8}));c.rotation.x=Math.PI/2;c.position.copy(p.position);c.position.y=.35;scene.add(c);}
 const portal=new THREE.Mesh(new THREE.TorusGeometry(3.3,.3,18,64),new THREE.MeshBasicMaterial({color:0x9b5cff,transparent:true,opacity:.9,blending:THREE.AdditiveBlending}));portal.position.set(0,3,0);scene.add(portal);const inner=new THREE.Mesh(new THREE.CircleGeometry(3,48),new THREE.MeshBasicMaterial({color:0x4c1d95,transparent:true,opacity:.42,side:THREE.DoubleSide}));inner.position.set(0,3,0);scene.add(inner);
 const title=document.createElement('div');title.id='selectionPanel';title.innerHTML='<h1>ELIGE TU ELEMENTO</h1><p>Corre hacia una esencia. El portal te absorberá cuando termine la cuenta.</p><div id="elementButtons"></div>';document.body.appendChild(title);const buttons=title.querySelector('#elementButtons');Object.entries(ELEMENTS).forEach(([k,E])=>{const b=document.createElement('button');b.innerHTML=`<span>${E.emoji}</span><strong>${E.name}</strong><small>${ATTACKS[k][0].name} · ${ATTACKS[k][1].name}</small>`;b.onclick=()=>choose(k);buttons.appendChild(b);});
}
function choose(k){if(state.selected)return;state.selected=k;ui.element({emoji:ELEMENTS[k].emoji,name:ELEMENTS[k].name,attacks:ATTACKS[k]});document.querySelector('#selectionPanel')?.remove();ui.objective('¡CORRE AL PORTAL!');spawnBattle();}
function spawnBattle(){state.phase='battle';state.time=120;scene.clear();scene.add(new THREE.HemisphereLight(0x8ab8ff,0x17100c,1));scene.add(sun);map=new ElementalMap(scene); player=new ELEMENTS[state.selected].klass({isPlayer:true});player.group.position.set(0,18,0);scene.add(player.group);players=[player]; for(let i=0;i<3;i++){const k=['fuego','agua','tierra','aire'][i];const c=new ELEMENTS[k].klass({isPlayer:false});c.group.position.set((i-1.5)*10,0,10+Math.random()*10);scene.add(c.group);players.push(c);} state.parachute= true;ui.objective('CAÍDA ELEMENTAL · abre tu paracaídas');document.body.classList.add('inbattle');}
function attack(){if(!player)return;const E=ELEMENTS[state.selected];const p=player.group.position.clone();const orb=new THREE.Mesh(new THREE.SphereGeometry(.28,12,10),new THREE.MeshBasicMaterial({color:E.color,blending:THREE.AdditiveBlending}));orb.position.copy(p);orb.position.z-=1;scene.add(orb);let t=0;const tick=()=>{t+=.04;orb.position.z-=.7;orb.scale.setScalar(1+t*1.5);if(t<1.3)requestAnimationFrame(tick);else scene.remove(orb)};tick();}
function collapse(){if(!map)return;const r=9-Math.min(7,(120-state.time)/15);map.collapse(r);ui.objective('⚠️ EL MAPA SE FRACTURA');}
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key===' ')attack();});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.05),t=clock.elapsedTime;if(state.phase==='lobby'){camera.position.y=26;camera.position.z=34;camera.lookAt(0,0,0);state.time=Math.max(0,state.time-dt);ui.timer(state.time);if(state.time<=0&&!state.selected){choose(['fuego','agua','tierra','aire'][Math.floor(Math.random()*4)]);}}else{state.time=Math.max(0,state.time-dt);ui.timer(state.time); if(player){const dir=new THREE.Vector3((keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),0,(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0));if(dir.lengthSq())dir.normalize().multiplyScalar(8);player.velocity.lerp(dir,.16);if(state.parachute){player.group.position.y=Math.max(0,player.group.position.y-dt*4);if(player.group.position.y===0){state.parachute=false;ui.objective('SOBREVIVE · saquea casas y domina tu elemento');}}player.update(dt,t);camera.position.lerp(new THREE.Vector3(player.group.position.x,player.group.position.y+20,player.group.position.z+22),.06);camera.lookAt(player.group.position.x,0,player.group.position.z);}map?.update(dt);if(Math.floor(state.time)%15===0&&Math.floor((state.time+dt)*10)!==Math.floor(state.time*10))collapse();}renderer.render(scene,camera);}
portalScene();ui.objective('ELIGE UN ELEMENTO');loop();
