import { ElementalMap } from './map/map.js';
import { FireCharacter } from './characters/fire.js';
import { WaterCharacter } from './characters/water.js';
import { EarthCharacter } from './characters/earth.js';
import { AirCharacter } from './characters/air.js';
import { LightningCharacter } from './characters/lightning.js';
import { IceCharacter } from './characters/ice.js';
import { NatureCharacter } from './characters/nature.js';
import { MetalCharacter } from './characters/metal.js';

const ELEMENTS={fuego:{name:'Fuego',emoji:'🔥',color:0xff4d00,glow:0xffa000,klass:FireCharacter,desc:'Quemadura y daño explosivo'},agua:{name:'Agua',emoji:'💧',color:0x29aaff,glow:0x8be7ff,klass:WaterCharacter,desc:'Control y curación'},tierra:{name:'Tierra',emoji:'🪨',color:0xb27a3e,glow:0xe2b36c,klass:EarthCharacter,desc:'Defensa y derribo'},aire:{name:'Aire',emoji:'🌀',color:0xbceeff,glow:0xffffff,klass:AirCharacter,desc:'Movilidad y empuje'},rayo:{name:'Rayo',emoji:'⚡',color:0x8b6cff,glow:0xffee74,klass:LightningCharacter,desc:'Cadena y aturdimiento'},hielo:{name:'Hielo',emoji:'❄️',color:0x66cfff,glow:0xe7ffff,klass:IceCharacter,desc:'Congelación y control'},naturaleza:{name:'Naturaleza',emoji:'🌿',color:0x35c96b,glow:0xa5ff9f,klass:NatureCharacter,desc:'Regeneración y veneno'},metal:{name:'Metal',emoji:'⚙️',color:0x8e9aa8,glow:0xe5f4ff,klass:MetalCharacter,desc:'Armadura y golpes pesados'}};
const START=['fuego','agua','tierra','aire'];
const state={phase:'selection',selected:null,time:18,mastery:JSON.parse(localStorage.getItem('fe_mod_mastery')||'{}'),collapse:0,score:0};
const canvas=document.querySelector('#game');const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputEncoding=THREE.sRGBEncoding;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x07101b);scene.fog=new THREE.FogExp2(0x07101b,.0028);const camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,1200);const hemi=new THREE.HemisphereLight(0x8ab8ff,0x17100c,1.15);const sun=new THREE.DirectionalLight(0xffe6c4,2.1);sun.position.set(-45,75,25);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(hemi,sun);
let map=null,player=null,team=[],clock=new THREE.Clock(),keys={},particles=[],loot=[],portal=null,portalCore=null,parachute=null,zone=null,shake=0,attackCooldown=0;const $=s=>document.querySelector(s);function uiText(id,text){const e=$(id);if(e)e.textContent=text}function setPhase(text,time){uiText('#phaseMod',text);uiText('#timerMod',Math.max(0,Math.ceil(time)))}function saveMastery(){localStorage.setItem('fe_mod_mastery',JSON.stringify(state.mastery))}function addMastery(el,n=2){state.mastery[el]=(state.mastery[el]||0)+n;saveMastery()}function mat(c,e=0){return new THREE.MeshStandardMaterial({color:c,roughness:.72,metalness:.12,emissive:e,emissiveIntensity:.3})}function glow(c,o=.7){return new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:o,blending:THREE.AdditiveBlending,depthWrite:false})}
function clearWorld(){while(scene.children.length)scene.remove(scene.children[0]);scene.add(hemi,sun);particles=[];loot=[];parachute=null;zone=null}
function makePortal(){const g=new THREE.Group();const platform=new THREE.Mesh(new THREE.CylinderGeometry(20,21,.7,64),mat(0x101725,0x24164d));platform.position.y=-.35;g.add(platform);portal=new THREE.Mesh(new THREE.TorusGeometry(4.2,.42,18,80),glow(0xb66cff,.9));portal.position.y=4;g.add(portal);portalCore=new THREE.Mesh(new THREE.CircleGeometry(3.8,64),new THREE.MeshBasicMaterial({color:0x2a0d58,transparent:true,opacity:.62,side:THREE.DoubleSide,blending:THREE.AdditiveBlending}));portalCore.position.y=4;g.add(portalCore);START.forEach((k,i)=>{const E=ELEMENTS[k],a=i*Math.PI/2-Math.PI/4,ped=new THREE.Mesh(new THREE.CylinderGeometry(1.25,1.55,.6,24),mat(0x161b25,E.color));ped.position.set(Math.cos(a)*8,0,Math.sin(a)*8);g.add(ped);const orb=new THREE.Mesh(new THREE.IcosahedronGeometry(.65,1),glow(E.color,.85));orb.position.set(ped.position.x,.95,ped.position.z);g.add(orb)});scene.add(g);camera.position.set(0,22,31);camera.lookAt(0,2,0);buildSelectionUI()}
function buildSelectionUI(){const panel=$('#selectionMod');panel.innerHTML='<div class="eyebrow">PRÓLOGO · 4 ESENCIAS</div><h1>ELIGE TU ELEMENTO</h1><p>Escoge rápido. Cuando el portal despierte, quien no tenga esencia será arrastrado.</p><div class="elementGrid"></div><div class="selectionTip">1–4 para elegir · después podrás dominar nuevos elementos</div>';panel.style.display='flex';const grid=panel.querySelector('.elementGrid');START.forEach((k,i)=>{const E=ELEMENTS[k],b=document.createElement('button');b.className='elementChoice';b.innerHTML=`<span class="bigEmoji">${E.emoji}</span><span><b>${E.name}</b><small>${E.desc}</small></span><kbd>${i+1}</kbd>`;b.onclick=()=>choose(k);grid.appendChild(b)})}
function choose(k){if(state.selected)return;state.selected=k;addMastery(k,0);$('#selectionMod').style.display='none';startDrop()}
function buildTeam(){team=[];const order=[state.selected,...START.filter(k=>k!==state.selected)];order.forEach((k,i)=>{const c=new ELEMENTS[k].klass({isPlayer:i===0});c.group.scale.setScalar(i===0?1.15:1);c.group.position.set(i===0?0:(i-1.5)*6,18,i===0?0:-4);scene.add(c.group);team.push(c)});player=team[0]}
function startDrop(){state.phase='drop';state.time=9;clearWorld();scene.fog=new THREE.FogExp2(0x081321,.0031);map=new ElementalMap(scene);buildTeam();makeParachute();uiText('#objectiveMod','ATERRIZA · muévete con WASD o flechas');document.body.classList.add('battleMode')}
function makeParachute(){const g=new THREE.Group(),E=ELEMENTS[state.selected],canopy=new THREE.Mesh(new THREE.SphereGeometry(4.3,24,12,0,Math.PI*2,0,Math.PI*.48),new THREE.MeshStandardMaterial({color:E.color,emissive:E.glow,emissiveIntensity:.35,roughness:.55,side:THREE.DoubleSide}));canopy.scale.y=.62;canopy.position.y=6;g.add(canopy);[-2.6,-1.3,0,1.3,2.6].forEach(x=>{const rope=new THREE.Mesh(new THREE.CylinderGeometry(.018,.018,3.2,5),glow(0xffffff,.65));rope.position.set(x*.65,4.3,0);g.add(rope)});g.position.y=1;player.group.add(g);parachute=g}
function spawnLoot(){const types=[['cura',0x39d98a],['habilidad',0xc17aff],['escudo',0x62bfff],['velocidad',0xffd24d]];for(let i=0;i<24;i++){const a=Math.random()*Math.PI*2,r=10+Math.random()*82,k=types[i%4],p=new THREE.Mesh(new THREE.OctahedronGeometry(.34,0),glow(k[1],.85));p.position.set(Math.cos(a)*r,.65,Math.sin(a)*r);p.userData.type=k[0];scene.add(p);loot.push(p)}}
function makeZone(){const g=new THREE.Group(),r=105;const ring=new THREE.Mesh(new THREE.RingGeometry(r-.7,r,128),glow(0xff3d55,.9));ring.rotation.x=-Math.PI/2;ring.position.y=.2;g.add(ring);scene.add(g);zone={group:g,r,ring}}
function startBattle(){state.phase='battle';state.time=180;spawnLoot();makeZone();if(parachute){player.group.remove(parachute);parachute=null}uiText('#objectiveMod','SOBREVIVE · saquea las casas y domina tu elemento')}
function burst(pos,color,count=12,scale=1){for(let i=0;i<count;i++){const p=new THREE.Mesh(new THREE.SphereGeometry(.045+Math.random()*.05,5,5),glow(color,.9));p.position.copy(pos);p.userData={v:new THREE.Vector3((Math.random()-.5)*scale,(Math.random()-.1)*scale,(Math.random()-.5)*scale),life:.35+Math.random()*.55};scene.add(p);particles.push(p)}}
function attack(){if(state.phase!=='battle'||attackCooldown>0)return;attackCooldown=.42;const E=ELEMENTS[state.selected],p=player.group.position.clone();p.y+=1;const orb=new THREE.Mesh(new THREE.IcosahedronGeometry(.25,1),glow(E.color,1));orb.position.copy(p);scene.add(orb);let life=0;const fly=()=>{life+=.035;orb.position.z-=1;orb.scale.setScalar(1+life);if(life<1.4){burst(orb.position,E.glow,1,.3);requestAnimationFrame(fly)}else{scene.remove(orb);burst(orb.position,E.glow,25,2.5)}};fly();state.score+=10;addMastery(state.selected,1)}
function special(){if(state.phase!=='battle'||attackCooldown>0)return;attackCooldown=2.5;const E=ELEMENTS[state.selected],p=player.group.position.clone(),ring=new THREE.Mesh(new THREE.RingGeometry(.5,5.5,64),glow(E.color,.65));ring.rotation.x=-Math.PI/2;ring.position.set(p.x,.12,p.z);scene.add(ring);burst(p,E.glow,60,5);state.score+=35;addMastery(state.selected,3);setTimeout(()=>scene.remove(ring),700)}
function useLoot(o){const t=o.userData.type;if(t==='cura')player.health=Math.min(100,player.health+28);if(t==='escudo')player.shield=5;if(t==='velocidad')player.speedBoost=6;if(t==='habilidad'){state.score+=25;addMastery(state.selected,5)}uiText('#feedMod',t==='cura'?'✚ Cura +28':t==='escudo'?'⬟ Escudo activo':t==='velocidad'?'➤ Velocidad +':'✦ Habilidad +5 dominio');burst(o.position,ELEMENTS[state.selected].glow,18,2);scene.remove(o);loot=loot.filter(x=>x!==o)}
function updatePlayers(dt,t){const d=new THREE.Vector3((keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),0,(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0));if(d.lengthSq())d.normalize();const speed=player.speedBoost>0?12:8;player.velocity.lerp(d.multiplyScalar(speed),Math.min(1,dt*8));player.update(dt,t);player.group.position.x=Math.max(-112,Math.min(112,player.group.position.x));player.group.position.z=Math.max(-112,Math.min(112,player.group.position.z));if(player.speedBoost>0)player.speedBoost-=dt;team.slice(1).forEach((c,i)=>{const target=new THREE.Vector3(Math.sin(t*.45+i)*20,0,Math.cos(t*.35+i)*20);c.velocity.lerp(target.sub(c.group.position).multiplyScalar(.4),.025);c.update(dt,t)});if(state.phase==='drop'){player.group.position.y=Math.max(0,player.group.position.y-dt*5.8);team.slice(1).forEach(c=>c.group.position.y=Math.max(0,c.group.position.y-dt*5.5));if(player.group.position.y<=.01)startBattle()}camera.position.lerp(new THREE.Vector3(player.group.position.x,player.group.position.y+15,player.group.position.z+19),.075);camera.lookAt(player.group.position.x,0,player.group.position.z)}
function updateFracture(){if(!zone||state.phase!=='battle')return;const elapsed=180-state.time,stage=Math.min(7,Math.floor(elapsed/20));if(stage>state.collapse){state.collapse=stage;const r=105-stage*12;zone.r=r;map.collapse(r);zone.ring.scale.set(r/105,r/105,1);uiText('#objectiveMod',`⚠ FRACTURA ${stage}/7 · el terreno exterior se rompe`);shake=.7;burst(new THREE.Vector3(),0xff3d55,35,9)}if(Math.hypot(player.group.position.x,player.group.position.z)>zone.r)player.damage(.35)}
function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.05),t=clock.elapsedTime;attackCooldown=Math.max(0,attackCooldown-dt);if(state.phase==='selection'){state.time=Math.max(0,state.time-dt);setPhase('EL PORTAL DESPIERTA',state.time);portal.rotation.z+=dt*.5;portalCore.rotation.z-=dt*.3;portalCore.scale.setScalar(1+Math.sin(t*4)*.035);if(state.time<=0&&!state.selected)choose(START[Math.floor(Math.random()*4)])}else{state.time=Math.max(0,state.time-dt);setPhase(state.phase==='drop'?'DESCENSO ELEMENTAL':'ZONA DE FRACTURA',state.time);updatePlayers(dt,t);map?.update(dt);updateFracture();if(state.phase==='battle'){loot.forEach(o=>{o.rotation.y+=dt*2;o.position.y=.62+Math.sin(t*3+o.position.x)*.1;if(player.group.position.distanceTo(o.position)<1.5)useLoot(o)});if(state.time<=0){state.phase='end';addMastery(state.selected,12);uiText('#objectiveMod','VICTORIA · tu dominio elemental ha aumentado')}}}particles.forEach(p=>{p.position.addScaledVector(p.userData.v,dt);p.userData.v.y-=dt*3;p.userData.life-=dt;if(p.userData.life<=0)scene.remove(p)});particles=particles.filter(p=>p.parent);if(shake>0){shake-=dt;camera.position.x+=(Math.random()-.5)*shake;camera.position.y+=(Math.random()-.5)*shake}uiText('#hpMod',`HP ${Math.ceil(player?.health||100)}`);uiText('#scoreMod',`✦ ${state.score}`);renderer.render(scene,camera)}
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.code==='Space')attack();if(e.key.toLowerCase()==='e')special();START.forEach((k,i)=>{if(e.key===String(i+1))choose(k)})});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);addEventListener('pointerdown',e=>{if(e.target===canvas&&state.phase==='battle')attack()});addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});makePortal();setPhase('EL PORTAL DESPIERTA',state.time);uiText('#objectiveMod','ELIGE TU ELEMENTO');loop();
