export class ElementalMap{
 constructor(scene){this.scene=scene;this.size=120;this.tiles=[];this._build()}
 _mat(c,e=0,rough=.75,metal=.05){return new THREE.MeshStandardMaterial({color:c,roughness:rough,metalness:metal,emissive:e,emissiveIntensity:.25})}
 _build(){const count=17,step=7,ground=this._mat(0x26362f);for(let x=-count;x<=count;x++)for(let z=-count;z<=count;z++){const wx=x*step,wz=z*step,r=Math.hypot(wx,wz);if(r>120)continue;const tile=new THREE.Mesh(new THREE.BoxGeometry(step-.16,.62,step-.16),ground);tile.position.set(wx,(Math.random()-.5)*.16,wz);tile.receiveShadow=true;tile.userData={radius:r,broken:false};this.scene.add(tile);this.tiles.push(tile)}this._roads();this._landmarks();this._trees();this._lootHouses()}
 _roads(){const roadMat=this._mat(0x4a463f,.02,.95);for(let i=-1;i<=1;i++){const road=new THREE.Mesh(new THREE.BoxGeometry(8,.05,235),roadMat);road.position.set(i*34,.36,0);this.scene.add(road);const cross=new THREE.Mesh(new THREE.BoxGeometry(235,.052,7),roadMat);cross.position.set(0,.365,i*34);this.scene.add(cross)}for(let i=-2;i<=2;i++){const mark=new THREE.Mesh(new THREE.BoxGeometry(1,.06,12),this._mat(0xb59d65));mark.position.set(i*8,.41,0);this.scene.add(mark)}}
 _landmarks(){const places=[[-58,-48,'Pueblo de Ceniza',false], [55,-45,'Lago Espejo',false],[-48,48,'Bosque Antiguo',false],[48,48,'Ruinas del Nexo',false],[0,0,'Santuario Elemental',true]];places.forEach(([x,z,name,central],i)=>{if(name==='Lago Espejo'){const lake=new THREE.Mesh(new THREE.CircleGeometry(16,48),new THREE.MeshStandardMaterial({color:0x236b83,transparent:true,opacity:.78,roughness:.18,metalness:.35}));lake.rotation.x=-Math.PI/2;lake.position.set(x,.43,z);this.scene.add(lake);for(let n=0;n<8;n++){const c=new THREE.Mesh(new THREE.OctahedronGeometry(.5+Math.random()*.6),this._mat(0x69d9e8,0x2aa0b8,.3));const a=Math.random()*Math.PI*2,r=13+Math.random()*5;c.position.set(x+Math.cos(a)*r,1,z+Math.sin(a)*r);this.scene.add(c)}return}const base=new THREE.Mesh(new THREE.CylinderGeometry(central?8:5,central?8.5:5.5,.7,10),this._mat(central?0x4a285d:0x4b443b));base.position.set(x,.36,z);this.scene.add(base);this._building(x,z,name,central)})}
 _building(x,z,name,central=false){const w=central?7:5,h=central?7:3.4,body=new THREE.Mesh(new THREE.BoxGeometry(w,h,w*.8),this._mat(central?0x24182d:0x42362d));body.position.set(x,h/2+.55,z);body.castShadow=true;this.scene.add(body);const roof=new THREE.Mesh(new THREE.ConeGeometry(w*.78,2.5,5),this._mat(central?0x7d3c2e:0x251b1b));roof.position.set(x,h+1.65,z);roof.castShadow=true;this.scene.add(roof);for(const sx of [-1,1]){const win=new THREE.Mesh(new THREE.BoxGeometry(1.05,.8,.05),this._mat(0x17253a,0x65aaff));win.position.set(x+sx*w*.22,1.7,z+w*.405);this.scene.add(win)}body.userData.landmark={name}}
 _trees(){for(let i=0;i<88;i++){const a=Math.random()*Math.PI*2,r=18+Math.random()*94,x=Math.cos(a)*r,z=Math.sin(a)*r;if(r>108||Math.abs(x)<8&&Math.abs(z)<8)continue;const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.16,.23,1.7,6),this._mat(0x3d291d));trunk.position.set(x,.9,z);const crown=new THREE.Mesh(new THREE.DodecahedronGeometry(1.1+Math.random()*.8,0),this._mat(i%3?0x274d3b:0x316044));crown.position.set(x,2.15,z);crown.castShadow=true;this.scene.add(trunk,crown)}}
 _lootHouses(){const spots=[[-18,-22],[20,-10],[-23,14],[17,20],[0,-30],[29,8],[-34,-5]];spots.forEach(([x,z],i)=>this._building(x,z,['Casa de Cura','Arsenal','Santuario','Tienda Arcana'][i%4]))}
 collapse(radius){this.tiles.forEach(tile=>{if(!tile.userData.broken&&tile.userData.radius>radius){tile.userData.broken=true;tile.userData.breakT=0;tile.userData.fallX=(Math.random()-.5)*.7;tile.userData.fallZ=(Math.random()-.5)*.7}})}
 update(dt){this.tiles.forEach(t=>{if(t.userData.broken){t.userData.breakT+=dt;t.rotation.x+=dt*(.45+t.userData.fallX);t.rotation.z+=dt*(.35+t.userData.fallZ);t.position.y-=dt*2.8;if(t.userData.breakT>1.8)this.scene.remove(t)}})}
}
